"""9

Revision ID: 55524d56daed
Revises: 94606ee92462
Create Date: 2023-05-15 20:09:39.746410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55524d56daed'
down_revision = '94606ee92462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
