"""2

Revision ID: 596b2d15ae1e
Revises: 0f25fe401892
Create Date: 2023-05-15 19:26:56.974549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596b2d15ae1e'
down_revision = '0f25fe401892'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
