"""Updated photo table

Revision ID: 7f28bd30740a
Revises: 506bb600a6d9
Create Date: 2023-05-14 17:11:24.969475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f28bd30740a'
down_revision = '506bb600a6d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
