"""4

Revision ID: 8e5c143fa9bd
Revises: f49f705c2b74
Create Date: 2023-05-15 19:29:48.361718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5c143fa9bd'
down_revision = 'f49f705c2b74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
