"""8

Revision ID: 94606ee92462
Revises: 756195200d06
Create Date: 2023-05-15 20:06:14.009079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94606ee92462'
down_revision = '756195200d06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ban_status', sa.Boolean(), nullable=True))
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'ban_status')
    # ### end Alembic commands ###
