"""12

Revision ID: 948b4a7e4a9c
Revises: e20aabad0050
Create Date: 2023-05-23 17:28:44.585783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948b4a7e4a9c'
down_revision = 'e20aabad0050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photorating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('photos', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('rated_by', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'rated_by')
    op.drop_column('photos', 'average_rating')
    op.drop_table('photorating')
    # ### end Alembic commands ###
