"""6

Revision ID: 99b184373c3d
Revises: a50ff0cd3721
Create Date: 2023-05-15 19:48:10.262299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b184373c3d'
down_revision = 'a50ff0cd3721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
