"""5

Revision ID: a50ff0cd3721
Revises: 8e5c143fa9bd
Create Date: 2023-05-15 19:46:40.508732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50ff0cd3721'
down_revision = '8e5c143fa9bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
