"""added photo to photo model

Revision ID: dd389954b368
Revises: 215416483919
Create Date: 2023-05-14 08:42:36.911022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd389954b368'
down_revision = '215416483919'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photo', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'photo')
    # ### end Alembic commands ###
